// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
	"hub/internal/application/listener"
	"hub/internal/application/radio"
	reaction2 "hub/internal/application/reaction"
	"hub/internal/application/shared"
	"hub/internal/application/statistics"
	track2 "hub/internal/application/track"
	"hub/internal/config"
	"hub/internal/database"
	"hub/internal/domain/reaction"
	"hub/internal/domain/track"
	"hub/internal/infrastructure/cache"
	"hub/internal/infrastructure/events"
	"hub/internal/infrastructure/icecast"
	"hub/internal/infrastructure/metrics"
	"hub/internal/infrastructure/persistence/postgres"
	"hub/internal/infrastructure/scheduler"
	"hub/internal/interfaces/http/handler"
	"hub/internal/interfaces/http/server"
	"hub/internal/logger"
)

// Injectors from wire.go:

func InitializeApp() (*Application, func(), error) {
	config := ProvideConfig()
	logger := ProvideLogger(config)
	database := ProvideDatabase(config, logger)
	pool := ProvidePool(database)
	trackRepository := ProvideTrackRepository(pool)
	repository := ProvideTrackDomainRepository(trackRepository)
	eventPublisher := ProvideEventPublisher()
	upsertTrackHandler := ProvideUpsertTrackHandler(repository, eventPublisher)
	getTrackHandler := ProvideGetTrackHandler(repository)
	trackHandler := ProvideTrackHandler(upsertTrackHandler, getTrackHandler)
	reactionRepository := ProvideReactionRepository(pool)
	addReactionHandler := ProvideAddReactionHandler(reactionRepository, repository, eventPublisher)
	checkReactionHandler := ProvideCheckReactionHandler(reactionRepository)
	reactionHandler := ProvideReactionHandler(addReactionHandler, checkReactionHandler)
	client, err := ProvideIcecastClient(config)
	if err != nil {
		return nil, nil, err
	}
	service := ProvideRadioService(client)
	radioHandler := ProvideRadioHandler(service)
	statisticsRepository := ProvideStatisticsRepository(pool)
	statisticsService := ProvideStatisticsService(statisticsRepository)
	statisticsHandler := ProvideStatisticsHandler(statisticsService)
	cache, err := ProvideCache(config, logger)
	if err != nil {
		return nil, nil, err
	}
	redisClient := ProvideRedisClient(cache)
	healthHandler := ProvideHealthHandler(pool, redisClient)
	router := ProvideRouter(trackHandler, reactionHandler, radioHandler, statisticsHandler, healthHandler)
	server := ProvideServer(router, logger)
	listenerRepository := ProvideListenerRepository(pool)
	listenerAdapter := ProvideListenerAdapter(listenerRepository)
	trackListenerAdapter := ProvideTrackListenerAdapter(trackRepository)
	listenerService := ProvideListenerService(client, listenerAdapter, trackListenerAdapter, logger)
	scheduler := ProvideScheduler(listenerService, logger)
	application := ProvideApplication(config, logger, database, server, scheduler)
	return application, func() {
	}, nil
}

func InitializeMigrateApp() (*MigrateApp, error) {
	config := ProvideConfig()
	logger := ProvideLogger(config)
	string2 := ProvideDSN(config)
	migrateApp := ProvideMigrateApp(config, logger, string2)
	return migrateApp, nil
}

// wire.go:

// Application holds all dependencies for the serve command
type Application struct {
	Config    config.Config
	Logger    *logger.Logger
	Database  database.Database
	Server    *server.Server
	Scheduler scheduler.Scheduler
}

// MigrateApp holds dependencies for migrate commands
type MigrateApp struct {
	Config config.Config
	Logger *logger.Logger
	DSN    string
}

func ProvideConfig() config.Config {
	return config.NewConfig()
}

func ProvideLogger(cfg config.Config) *logger.Logger {
	return logger.NewLogger(cfg.LogLevel())
}

func ProvideDSN(cfg config.Config) string {
	dsn, _, _ := cfg.DatabaseConnection()
	return dsn
}

func ProvideDatabase(cfg config.Config, log *logger.Logger) database.Database {
	dsn, minConns, maxConns := cfg.DatabaseConnection()
	return database.NewDatabase(dsn, minConns, maxConns, log)
}

func ProvidePool(db database.Database) *pgxpool.Pool {
	return db.Pool()
}

func ProvideEventPublisher() shared.EventPublisher {
	return events.NewInMemoryPublisher()
}

func ProvideCache(cfg config.Config, log *logger.Logger) (cache.Cache, error) {
	return cache.NewCache(cfg, log)
}

func ProvideRedisClient(c cache.Cache) *redis.Client {
	return c.Client()
}

func ProvideMetrics() *metrics.Metrics {
	return metrics.NewMetrics()
}

func ProvideUnitOfWork(pool *pgxpool.Pool) *postgres.UnitOfWork {
	return postgres.NewUnitOfWork(pool)
}

func ProvideTrackRepository(pool *pgxpool.Pool) *postgres.TrackRepository {
	return postgres.NewTrackRepository(pool)
}

func ProvideTrackDomainRepository(repo *postgres.TrackRepository) track.Repository {
	return repo
}

func ProvideReactionRepository(pool *pgxpool.Pool) reaction.Repository {
	return postgres.NewReactionRepository(pool)
}

func ProvideListenerRepository(pool *pgxpool.Pool) *postgres.ListenerRepository {
	return postgres.NewListenerRepository(pool)
}

func ProvideStatisticsRepository(pool *pgxpool.Pool) *postgres.StatisticsRepository {
	return postgres.NewStatisticsRepository(pool)
}

func ProvideListenerAdapter(repo *postgres.ListenerRepository) *postgres.ListenerAdapter {
	return postgres.NewListenerAdapter(repo)
}

func ProvideTrackListenerAdapter(repo *postgres.TrackRepository) *postgres.TrackListenerAdapter {
	return postgres.NewTrackListenerAdapter(repo)
}

func ProvideUpsertTrackHandler(repo track.Repository, pub shared.EventPublisher) *track2.UpsertTrackHandler {
	return track2.NewUpsertTrackHandler(repo, pub)
}

func ProvideGetTrackHandler(repo track.Repository) *track2.GetTrackHandler {
	return track2.NewGetTrackHandler(repo)
}

func ProvideAddReactionHandler(rr reaction.Repository, tr track.Repository, pub shared.EventPublisher) *reaction2.AddReactionHandler {
	return reaction2.NewAddReactionHandler(rr, tr, pub)
}

func ProvideCheckReactionHandler(rr reaction.Repository) *reaction2.CheckReactionHandler {
	return reaction2.NewCheckReactionHandler(rr)
}

func ProvideIcecastClient(cfg config.Config) (icecast.Client, error) {
	return icecast.NewClient(cfg)
}

func ProvideRadioService(ic icecast.Client) radio.Service {
	return radio.NewService(ic)
}

func ProvideStatisticsService(repo *postgres.StatisticsRepository) statistics.Service {
	return statistics.NewService(repo)
}

func ProvideListenerService(ic icecast.Client, la *postgres.ListenerAdapter, ta *postgres.TrackListenerAdapter, log *logger.Logger) listener.Service {
	return listener.NewService(ic, la, ta, log)
}

func ProvideTrackHandler(uh *track2.UpsertTrackHandler, gh *track2.GetTrackHandler) *handler.TrackHandler {
	return handler.NewTrackHandler(uh, gh)
}

func ProvideReactionHandler(ah *reaction2.AddReactionHandler, ch *reaction2.CheckReactionHandler) *handler.ReactionHandler {
	return handler.NewReactionHandler(ah, ch)
}

func ProvideRadioHandler(svc radio.Service) *handler.RadioHandler {
	return handler.NewRadioHandler(svc)
}

func ProvideStatisticsHandler(svc statistics.Service) *handler.StatisticsHandler {
	return handler.NewStatisticsHandler(svc)
}

func ProvideHealthHandler(pool *pgxpool.Pool, redisClient *redis.Client) *handler.HealthHandler {
	return handler.NewHealthHandler(pool, redisClient)
}

func ProvideRouter(th *handler.TrackHandler, rh *handler.ReactionHandler, rah *handler.RadioHandler, sh *handler.StatisticsHandler, hh *handler.HealthHandler) *server.Router {
	return server.NewRouter(th, rh, rah, sh, hh)
}

func ProvideServer(router *server.Router, log *logger.Logger) *server.Server {
	return server.NewServer(router, log)
}

func ProvideScheduler(ls listener.Service, log *logger.Logger) scheduler.Scheduler {
	return scheduler.NewScheduler(ls, log)
}

func ProvideApplication(cfg config.Config, log *logger.Logger, db database.Database, srv *server.Server, sched scheduler.Scheduler) *Application {
	return &Application{Config: cfg, Logger: log, Database: db, Server: srv, Scheduler: sched}
}

func ProvideMigrateApp(cfg config.Config, log *logger.Logger, dsn string) *MigrateApp {
	return &MigrateApp{Config: cfg, Logger: log, DSN: dsn}
}

var ProviderSet = wire.NewSet(
	ProvideConfig, ProvideLogger, ProvideDSN, ProvideDatabase, ProvidePool, ProvideEventPublisher,
	ProvideCache, ProvideRedisClient, ProvideMetrics, ProvideUnitOfWork,
	ProvideTrackRepository, ProvideTrackDomainRepository, ProvideReactionRepository,
	ProvideListenerRepository, ProvideStatisticsRepository,
	ProvideListenerAdapter, ProvideTrackListenerAdapter,
	ProvideUpsertTrackHandler, ProvideGetTrackHandler, ProvideAddReactionHandler, ProvideCheckReactionHandler,
	ProvideIcecastClient, ProvideRadioService, ProvideStatisticsService, ProvideListenerService,
	ProvideTrackHandler, ProvideReactionHandler, ProvideRadioHandler, ProvideStatisticsHandler, ProvideHealthHandler,
	ProvideRouter, ProvideServer, ProvideScheduler, ProvideApplication,
)

var MigrateProviderSet = wire.NewSet(ProvideConfig, ProvideLogger, ProvideDSN, ProvideMigrateApp)
